- hosts: all
  sudo: yes

  tasks:
  - name: Add repository for PHP 7.
    apt_repository: repo='ppa:ondrej/php'
  - name: install packages
    apt: name={{ item }} state=present
    with_items:
      - nginx
      - mysql-server
      - python-mysqldb
      - php7.1-common
      - php7.1-cli
      - php7.1-intl
      - php7.1-curl
      - php7.1-cgi
      - php7.1-fpm
      - php7.1-mysql
      - php7.1-gd
      - php7.1-mcrypt
      - php7.1-mbstring
  - name: Copy nginx site config file
    copy:
      src: ./nginx/default
      dest: /etc/nginx/sites-available/default
  - name: Copy database dump file
    copy:
      src: ./sql/sample-data.sql
      dest: /tmp
  - name: Restore database
    mysql_db:
      name: all
      login_user: root
      login_password: root
      state: import
      target: /tmp/sample-data.sql